-- CCP Escape Use YN
CREATE TABLE `CCP_ESC_YN` (
`DEVICE_ID` VARCHAR(20) NOT NULL COMMENT '장비코드', -- DEVICE_ID
`USE_YN`    CHAR(1)     NOT NULL COMMENT '사용유무', -- USE_YN
`REG_ID`    VARCHAR(15) NULL     COMMENT '등록자ID', -- REG_ID
PRIMARY KEY(DEVICE_ID)
)
COMMENT 'CCP Escape Use YN';
