-- CCP Limit
CREATE TABLE `CCP_LIMIT` (
`DEVICE_ID` VARCHAR(20)  NOT NULL COMMENT '장비코드', -- DEVICE_ID
`LMT_UP`    DECIMAL(10)  NULL     COMMENT '한계 상', -- LMT_UP
`LMT_DN`    DECIMAL(10)  NULL     COMMENT '한계 하', -- LMT_DN
`REMARK`    VARCHAR(100) NULL     COMMENT '비고', -- REMARK
`REG_ID`    VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID
`REG_DTM`   VARCHAR(14)  NULL     COMMENT '등록일시', -- REG_DTM
PRIMARY KEY(DEVICE_ID)
)
COMMENT 'CCP Limit';
