CREATE TABLE `CCP_DATA` (
`CCP_SEQ`   INT          NOT NULL AUTO_INCREMENT COMMENT '', -- CCP_SEQ
`DEVICE_ID` VARCHAR(10)  NULL COMMENT '장비코드', -- DEVICE_ID
`DATA`      VARCHAR(10)  NULL COMMENT '', -- DATA
`REG_DTM`   VARCHAR(14)  NULL COMMENT '등록일시', -- REG_DTM
PRIMARY KEY(CCP_SEQ)
)
COMMENT 'CCP Data';
