-- CCP Escape YN History
CREATE TABLE `CCP_ESC_YN_HIST` (
`DEVICE_ID` VARCHAR(20) NOT NULL COMMENT '장비코드', -- DEVICE_ID
`USE_YN`    CHAR(1)     NOT NULL COMMENT '사용유무', -- USE_YN
`REG_DTM`   VARCHAR(14) NOT NULL COMMENT '등록일시' -- REG_DTM
)
COMMENT 'CCP Escape YN History';
