CREATE TABLE `CCP_CD_INFO` (
`CCP_CD`   VARCHAR(20)  NOT NULL COMMENT 'CCP 코드', -- CCP_CD
`CCP_NM`   VARCHAR(200) NULL     COMMENT 'CCP 설명', -- CCP_NM
`TEMP_FR`  DECIMAL(10)  NULL     COMMENT '한계온도1', -- TEMP_FR
`TEMP_TO`  DECIMAL(10)  NULL     COMMENT '한계온도2', -- TEMP_TO
`BOIL_FR`  DECIMAL(10)  NULL     COMMENT '가열시간1', -- BOIL_FR
`BOIL_TO`  DECIMAL(10)  NULL     COMMENT '가열시간2', -- BOIL_TO
`CHK_TEMP` DECIMAL(10)  NULL     COMMENT '품온', -- CHK_TEMP
`REMARK`   VARCHAR(100) NULL     COMMENT '비고', -- REMARK
`REG_ID`   VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID
`REG_DTM`  VARCHAR(14)  NULL     COMMENT '등록일시', -- REG_DTM
PRIMARY KEY(CCP_CD)
)
COMMENT 'CCP Code Info';
