CREATE TABLE `COMM_CD` (
	`COMM1_CD` VARCHAR(10)  NOT NULL COMMENT '공통코드1', -- COMM1_CD 
	`COMM2_CD` VARCHAR(10)  NOT NULL COMMENT '공통코드2', -- COMM2_CD 
	`COMM2_NM` VARCHAR(100) NULL     COMMENT '코드이름', -- COMM2_NM 
	`REG_ID`   VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID 
	`REG_DTM`  VARCHAR(14)  NULL     COMMENT '등록일지', -- REG_DTM 
	PRIMARY KEY(COMM1_CD, COMM2_CD)
)
COMMENT 'Common Code';
