CREATE TABLE `COMP_INFO` (
	`COMP_ID`    VARCHAR(20)  NOT NULL COMMENT '사업자번호', -- COMP_ID
	`COMP_NM`    VARCHAR(60)  NULL     COMMENT '회사이름', -- COMP_NM
	`CEO_NM`     VARCHAR(60)  NULL     COMMENT '대표자명', -- CEO_NM
	`TEL_NO`     VARCHAR(20)  NULL     COMMENT '전화번호', -- TEL_NO
	`FAX_NO`     VARCHAR(20)  NULL     COMMENT '팩스번호', -- FAX_NO
	`URL`        VARCHAR(30)  NULL     COMMENT '홈페이지', -- URL
	`ZIP_CD`     VARCHAR(10)  NULL     COMMENT '우편번호', -- ZIP_CD
	`ADDR1`      VARCHAR(60)  NULL     COMMENT '주소1', -- ADDR1
	`ADDR2`      VARCHAR(60)  NULL     COMMENT '주소2', -- ADDR2
	`HACCP_ID`   VARCHAR(15)  NULL     COMMENT 'HACCP담당', -- HACCP_ID
	`HACCP_ITEM` VARCHAR(100) NULL     COMMENT 'HACCP품목', -- HACCP_ITEM
	`REG_ID`     VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID 
	`REG_DTM`    VARCHAR(14)  NULL     COMMENT '등록일지', -- REG_DTM 
	PRIMARY KEY(COMP_ID)
)
COMMENT 'Company Info';
