CREATE TABLE `ATT_FILE` (
	`ATT_DTM`  VARCHAR(14)  NOT NULL COMMENT '첨부일시', -- ATT_DTM
	`ATT_SEQ`  VARCHAR(3)   NOT NULL COMMENT '파일순번', -- ATT_SEQ
	`ATT_NM`   VARCHAR(200) NULL     COMMENT '파일명', -- ATT_NM
	`ATT_PATH` VARCHAR(400) NULL     COMMENT '경로명', -- ATT_PATH
	`FILE_SZ`  DECIMAL(12) NULL     DEFAULT  0 COMMENT '파일크기', -- File size
	`RMK`      VARCHAR(200) NULL     COMMENT '비고', -- Remark
	PRIMARY KEY(ATT_DTM, ATT_SEQ)
)
COMMENT 'Attachment File';
