CREATE TABLE `CUST_INFO` (
`COMP_ID`  VARCHAR(20)  NOT NULL COMMENT '사업자번호', 
`COMP_NM`  VARCHAR(60)  NULL     COMMENT '회사이름', 
`CEO_NM`   VARCHAR(60)  NULL     COMMENT '대표자명', 
`MOB_NO`   VARCHAR(20)  NULL     COMMENT '휴대폰번호', 
`CUST_NM`  VARCHAR(60)  NULL     COMMENT '담당자명', 
`CUST_NO`  VARCHAR(20)  NULL     COMMENT '담당자폰번호', 
`TEL_NO`   VARCHAR(20)  NULL     COMMENT '전화번호', 
`FAX_NO`   VARCHAR(20)  NULL     COMMENT '팩스번호', 
`SRH_INFO` VARCHAR(100) NULL     COMMENT '검색정보', 
`EMAIL`    VARCHAR(60)  NULL     COMMENT '이메일', 
`GRP_NM`   VARCHAR(100) NULL     COMMENT '그룹명', 
`ADDR`     VARCHAR(200) NULL     COMMENT '주소', 
`REMARK`   VARCHAR(300) NULL     COMMENT '비고', 
`USE_YN`   CHAR(1)      NULL     COMMENT '사용구분', 
`REG_ID`   VARCHAR(15)  NULL     COMMENT '등록자ID', 
`REG_DTM`  VARCHAR(14)  NULL     COMMENT '등록일시',
PRIMARY KEY(COMP_ID)
)
COMMENT 'Customer Information';

