CREATE TABLE `EDOC_FILE` (
	`DOC_ID`      INT          NOT NULL AUTO_INCREMENT COMMENT '문서ID', -- DOC_ID
	`TYPE_CD`     VARCHAR(20)  NULL     COMMENT '문서종류', -- TYPE_CD
	`DOC_NM`      VARCHAR(100) NULL     COMMENT '문서이름', -- DOC_NM
	`DOC_DESC`    VARCHAR(300) NULL     COMMENT '문서내용', -- DOC_DESC
	`DOC_HTML`    TEXT         NULL     COMMENT '문서형식', -- DOC_HTML
	`APP_VIEW`    TEXT         NULL     COMMENT '앱뷰', -- APP_VIEW
	`APP_INPUT`   TEXT         NULL     COMMENT '앱입력', -- APP_INPUT
	`APP_LIST`    TEXT         NULL     COMMENT '앱리스트', -- APP_LIST
	`PERIOD_CD`   VARCHAR(20)  NULL     COMMENT '주기코드', -- PERIOD_CD
	`PERIOD_DATA` VARCHAR(40)  NULL     COMMENT '주기자료', -- PERIOD_DATA
	`USE_YN`      CHAR(1)      NULL     COMMENT '사용유무', -- USE_YN
	`WORK_ID`     VARCHAR(15)  NULL     COMMENT '작업자ID', -- WORK_ID
	`APP_ID`      VARCHAR(15)  NULL     COMMENT '승인자ID', -- APP_ID
	`UPD_DTM`     VARCHAR(14)  NULL     COMMENT '수정일시', -- UPD_DTM
	PRIMARY KEY(DOC_ID)
)
COMMENT 'eDoc File';