-- eDoc File having HACCP
CREATE TABLE `EDOC_FILE_HACCP` (
`HACCP_SEQ` INT          NOT NULL AUTO_INCREMENT COMMENT '업무종류', -- TYPE_CD
`DOC_ID`    INT          NULL     COMMENT 'DOC_ID', -- DOC_ID
`APR_CD`    VARCHAR(20) NULL     COMMENT '결재승인코드', -- APR_CD > C10
`APP_DATA`  LONGTEXT     NULL     COMMENT 'APP 자료', -- APP_DATA
`REMARK`    VARCHAR(100) NULL     COMMENT '비고', -- REMARK
`USE_YN`    CHAR(1)      NULL     COMMENT '사용유무', -- USE_YN
`WORK_ID`   VARCHAR(15)  NULL     COMMENT '작업자ID', -- WORK_ID
`WORK_DTM`  VARCHAR(14)  NULL     COMMENT '작업일시', -- WORK_DTM
`APP_ID`    VARCHAR(15)  NULL     COMMENT '승인자ID', -- APP_ID
`APP_DTM`   VARCHAR(14)  NULL     COMMENT '작업일시', -- APP_DTM
PRIMARY KEY(HACCP_SEQ)
)
COMMENT 'eDoc File having HACCP';
