CREATE TABLE `HACCP_MST_FILE` (
	`REV_SEQ`     INT          NOT NULL AUTO_INCREMENT COMMENT '개정번호', -- REV_SEQ
	`REV_NO`      VARCHAR(10)  NULL     COMMENT 'REV_NO', -- REV_NO
	`REV_DT`      VARCHAR(8)   NULL     COMMENT '개정일자', -- REV_DT
	`ATT_DTM`     VARCHAR(14)  NULL     COMMENT '첨부화일', -- ATT_DTM
	`REV_CONTENT` VARCHAR(100) NULL     COMMENT '개정내용', -- REV_CONTENT
	`REV_REASON`  VARCHAR(100) NULL     COMMENT '개정사유', -- REV_REASON
	`REG_ID`      VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID 
	`REG_DTM`     VARCHAR(14)  NULL     COMMENT '등록일시', -- REG_DTM
	PRIMARY KEY(REV_SEQ)
)
COMMENT 'HACCP Master File';
