CREATE TABLE `ITEM_MST` (
`ITEM_ID`    VARCHAR(20)  NOT NULL COMMENT '자재 ID', -- ITEM_ID
`ITEM_NM`    VARCHAR(100) NULL     COMMENT '자재이름', -- ITEM_NM
`SPEC`       VARCHAR(100) NULL     COMMENT '규격', -- SPEC
`UNIT`       VARCHAR(20)  NULL     COMMENT '단위', -- UNIT
`QTY1`       DECIMAL(10)  NULL     COMMENT '당수량', -- QTY1
`QTY2`       DECIMAL(10)  NULL     COMMENT '봉수량', -- QTY2
`CONN_NO`    DECIMAL(10)  NULL     COMMENT '대표품목', -- CONN_NO
`CONN_QTY`   DECIMAL(10)  NULL     COMMENT '연결품목', -- CONN_QTY
`IN_AMT`     DECIMAL(10)  NULL     COMMENT '입고가', -- IN_AMT
`OUT_AMT`    DECIMAL(10)  NULL     COMMENT '출고가', -- OUT_AMT
`ITEM_CD`    VARCHAR(20)  NULL     COMMENT '자재구분', -- ITEM_CD > B10
`GRP1_CD`    VARCHAR(20)  NULL     COMMENT '그룹코드1', -- GRP1_CD > B11
`GRP2_CD`    VARCHAR(20)  NULL     COMMENT '그룹코드2', -- GRP2_CD > B12
`GRP3_CD`    VARCHAR(20)  NULL     COMMENT '그룹코드3', -- GRP3_CD > B13
`USE_YN`     CHAR(1)      NULL     COMMENT '사용구분', -- USE_YN
`PROCESS_CD` VARCHAR(20)  NULL     COMMENT '공정코드', -- PROCESS_CD > B14
`UNIT1_NM`   VARCHAR(30)  NULL     COMMENT '대단위명', -- UNIT1_NM
`UNIT1_QTY`  DECIMAL(10)  NULL     COMMENT '대단위수', -- UNIT1_QTY
`UNIT2_NM`   VARCHAR(30)  NULL     COMMENT '중단위명', -- UNIT2_NM
`UNIT2_QTY`  DECIMAL(10)  NULL     COMMENT '중단위수', -- UNIT2_QTY
`UNIT3_NM`   VARCHAR(30)  NULL     COMMENT '소단위명', -- UNIT3_NM
`UNIT3_QTY`  DECIMAL(10)  NULL     COMMENT '소단위수', -- UNIT3_QTY
`REG_ID`     VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID 
`REG_DTM`    VARCHAR(14)  NULL     COMMENT '등록일시', -- REG_DTM
PRIMARY KEY(ITEM_ID)
)
COMMENT 'Item Master';
