CREATE TABLE `JOB_ORD_DTL` (
`JOB_NO`    VARCHAR(20)  NOT NULL COMMENT '작업번호', -- JOB_NO
`ITEM_ID`   VARCHAR(20)  NOT NULL COMMENT '품목 ID', -- ITEM_ID
`SEQ_NO`    DECIMAL(10)  NOT NULL COMMENT 'PROC순번', -- SEQ_NO
`SEQ_NM`    VARCHAR(20)  NULL     COMMENT '순서이름', -- SEQ_NM
`PROC_CD`   VARCHAR(20)  NULL     COMMENT '공정코드', -- PROC_CD > B80
`PROC_NM`   VARCHAR(40)  NULL     COMMENT '공정이름', -- PROC_NM
`PROC_TIME` DECIMAL(5)   NULL     COMMENT '소요시간', -- PROC_TIME
`PROC_DTL`  VARCHAR(500) NULL     COMMENT '설명', -- PROC_DTL
`SRT_DTM`   VARCHAR(14)  NULL     COMMENT '시작시간', -- SRT_DTM
`END_DTM`   VARCHAR(14)  NULL     COMMENT '종료시간', -- END_DTM
`CHK1_DTM`  VARCHAR(14)  NULL     COMMENT '측정시간', -- CHK1_DTM
`CHK_TEMP`  DECIMAL(10)  NULL     COMMENT '측정온도', -- CHK1_TEMP
`CHK2_TIME` DECIMAL(10)  NULL     COMMENT '측정시간', -- CHK2_TIME
`CHK2_TEMP` DECIMAL(10)  NULL     COMMENT '측정온도', -- CHK2_TEMP
`SRC_CD`    VARCHAR(20)  NULL     COMMENT 'CCP 품목코드', -- SRC_CD
`CCP_CD`    VARCHAR(20)  NULL     COMMENT 'CCP코드', -- CCP_CD
`CCP_YN`    CHAR(1)      NULL     COMMENT 'CCP구분', -- CCP_YN
`REMARK`    VARCHAR(100) NULL     COMMENT '비고', -- REMARK
PRIMARY KEY(JOB_NO, ITEM_ID, SEQ_NO)
)
COMMENT 'Job Order Detail';
