CREATE TABLE `JOB_ORD_DTL_WORK` (
	`JOB_NO`  VARCHAR(20)  NOT NULL COMMENT '작업번호', -- JOB_NO
	`ITEM_ID` VARCHAR(20)  NOT NULL COMMENT '품목 ID', -- ITEM_ID
	`SEQ_NO`  DECIMAL(10)  NOT NULL COMMENT 'PROC순번', -- SEQ_NO
	`EMP_ID`  VARCHAR(15)  NOT NULL COMMENT '직원번호', -- EMP_ID
	`REMARK`  VARCHAR(100) NULL     COMMENT '비고', -- REMARK
	`REG_ID`  VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID
	`REG_DTM` VARCHAR(14)  NULL     COMMENT '등록일시', -- REG_DTM
PRIMARY KEY(JOB_NO, ITEM_ID, SEQ_NO, EMP_ID)
)
COMMENT 'Job Order Detail Worker';