CREATE TABLE `JOB_ORD_DTL` (
`JOB_NO`    VARCHAR(15)  NOT NULL COMMENT '작업번호', -- JOB_NO
`ITEM_ID`   VARCHAR(20)  NOT NULL COMMENT '자재 ID', -- ITEM_ID
`SEQ_NO`    INT(3)       NOT NULL COMMENT 'PROC순번', -- SEQ_NO
`SEQ_NM`    VARCHAR(20)  NULL     COMMENT '순서이름', -- SEQ_NM
`PROC_CD`   VARCHAR(20)  NULL     COMMENT '공정코드', -- PROC_CD
`PROC_NM`   VARCHAR(40)  NULL     COMMENT '공정이름', -- PROC_NM
`PROC_TIME` DECIMAL(5)   NULL     COMMENT '소요시간', -- PROC_TIME
`PROC_DTL`  VARCHAR(500) NULL     COMMENT '설명', -- PROC_DTL
`SRT_DTM`   VARCHAR(14)  NULL     COMMENT '시작시간', -- SRT_DTM
`END_DTM`   VARCHAR(14)  NULL     COMMENT '종료시간', -- END_DTM
`HACCP_CD`  VARCHAR(20)  NULL     COMMENT 'HACCP 품목코드', -- HACCP_CD
`HACCP_YN`  CHAR(1)      NULL     COMMENT 'HACCP YN', -- HACCP_YN
`REMARK`    VARCHAR(100) NULL     COMMENT '비고', -- REMARK
`REG_ID`    VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID
`REG_DTM`   VARCHAR(14)  NULL     COMMENT '등록일시',-- REG_DTM
PRIMARY KEY(JOB_NO, ITEM_ID, SEQ_NO)
)
COMMENT 'Job Order Detail';
