CREATE TABLE `JOB_ORD` (
`JOB_DT`   VARCHAR(8)   NOT NULL COMMENT '작업일자', -- JOB_DT
`SEQ_NO`   INT(3)       NOT NULL COMMENT '전표순번', -- SEQ_NO
`ITEM_ID`  VARCHAR(20)  NOT NULL COMMENT '자재 ID', -- ITEM_ID
`ORD_QTY`  DECIMAL(10)  NULL     COMMENT '지시수량', -- ORD_QTY
`PROD_QTY` DECIMAL(10)  NULL     COMMENT '생산수량', -- PROD_QTY
`ORD_NM`   VARCHAR(20)  NULL     COMMENT '담당자', -- ORD_NM
`BOM_VER`  VARCHAR(100) NULL     COMMENT 'BOM 버젼', -- BOM_VER
`FACT_CD`    VARCHAR(20)  NULL     COMMENT '생산공장코드', -- FACT_CD
`REMARK`   VARCHAR(100) NULL     COMMENT '비고', -- REMARK
`REG_ID`   VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID
`REG_DTM`  VARCHAR(14)  NULL     COMMENT '등록일시', -- REG_DTM
PRIMARY KEY(JOB_DT, SEQ_NO, ITEM_ID)
)
COMMENT 'Job Order';
