CREATE TABLE `JOB_ORD_BOM` (
`JOB_NO`   VARCHAR(20)  NOT NULL COMMENT '작업번호', -- JOB_NO
`ITEM_ID`  VARCHAR(20)  NULL     COMMENT '자재 ID', -- ITEM_ID
`ITEM2_ID` VARCHAR(20)  NOT NULL COMMENT '자재2 ID', -- ITEM2_ID
`ITEM2_NM` VARCHAR(100) NULL     COMMENT '자재2 이름', -- ITEM2_NM
`PROD_QTY` DECIMAL(10)  NULL     COMMENT '생산수량', -- PROD_QTY
`USE_QTY`  DECIMAL(10)  NULL     COMMENT '소모수량' -- USE_QTY
PRIMARY KEY(JOB_NO , ITEM_ID , ITEM2_ID)
)
COMMENT 'Job Order BOM';
