CREATE TABLE `JOB_ORD_DTL_SUB` (
`JOB_NO`     VARCHAR(15)  NOT NULL COMMENT '작업번호', -- JOB_NO
`ITEM_ID`    VARCHAR(20)  NOT NULL COMMENT '자재 ID', -- ITEM_ID
`SEQ_NO`     INT(3)       NOT NULL COMMENT 'SEQ_NO', -- SEQ_NO
`SUB_SEQ_NO` INT(3)       NOT NULL COMMENT '동시작업순서', -- SUB_SEQ_NO
`SEQ_NM`     VARCHAR(20)  NULL     COMMENT '순서이름', -- SEQ_NM
`PROC_CD`    VARCHAR(20)  NULL     COMMENT '공정코드', -- PROC_CD
`PROC_NM`    VARCHAR(40)  NULL     COMMENT '공정이름', -- PROC_NM
`PROC_DTL`   VARCHAR(500) NULL     COMMENT '설명', -- PROC_DTL
`REMARK`     VARCHAR(100) NULL     COMMENT '비고', -- REMARK
`REG_ID`     VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID
`REG_DTM`    VARCHAR(14)  NULL     COMMENT '등록일시', -- REG_DTM
PRIMARY KEY(JOB_NO, ITEM_ID, SEQ_NO, SUB_SEQ_NO)
)
COMMENT 'Job Order Detail Sub';
