CREATE TABLE `JOB_ORD` (
`JOB_NO`   VARCHAR(20)  NOT NULL COMMENT '작업번호', -- JOB_NO
`ITEM_ID`  VARCHAR(20)  NULL     COMMENT '자재 ID', -- ITEM_ID
`ITEM_NM`  VARCHAR(100) NULL     COMMENT '자재 이름', -- ITEM_NM
`ORD_QTY`  DECIMAL(10)  NULL     COMMENT '지시수량', -- ORD_QTY
`PROD_QTY` DECIMAL(10)  NULL     COMMENT '생산수량', -- PROD_QTY
`ORD_NM`   VARCHAR(20)  NULL     COMMENT '담당자', -- ORD_NM
`BOM_VER`  VARCHAR(100) NULL     COMMENT 'BOM 버젼', -- BOM_VER
`FACT_CD`  VARCHAR(20)  NULL     COMMENT '공장코드', -- FACT_CD
`REMARK`   VARCHAR(100) NULL     COMMENT '비고', -- REMARK
`REG_ID`   VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID
`REG_DTM`  VARCHAR(14)  NULL     COMMENT '등록일시' -- REG_DTM
PRIMARY KEY(JOB_NO , ITEM_ID)
)
COMMENT 'Job Order';
