CREATE TABLE `LOGIN_HIST` (
	`USER_ID`    VARCHAR(15) NOT NULL COMMENT '사용자 ID', -- USER_ID
	`LOGIN_DTM`  VARCHAR(14) NOT NULL COMMENT '로그인일시', -- LOGIN_DTM 
	`LOGOUT_DTM` VARCHAR(14) NULL     COMMENT '로그아웃일시', -- LOGOUT_DTM 
	`IP_ADDR`    VARCHAR(20) NULL     COMMENT '접속IP', -- IP_ADDR 
	PRIMARY KEY(USER_ID, LOGIN_DTM)
)
COMMENT 'Login History';
