CREATE TABLE `LOT_INFO` (
`DT_NO`    VARCHAR(20)  NOT NULL COMMENT '일자번호', -- DT_NO
`ITEM_ID`  VARCHAR(20)  NULL     COMMENT '품목 ID', -- ITEM_ID
`ITEM_NM`  VARCHAR(100) NULL     COMMENT '품목이름', -- ITEM_NM
`SPEC`     VARCHAR(100) NULL     COMMENT '규격', -- SPEC
`UNIT`     VARCHAR(20)  NULL     COMMENT '단위', -- UNIT
`ORIGIN`   VARCHAR(20)  NULL     COMMENT '원산지', -- ORIGIN
`LOT_NO`   VARCHAR(20)  NULL     COMMENT '로트시리얼', -- LOT_NO
`QTY`      DECIMAL(10)  NULL     COMMENT '수량', -- QTY
`ACC_CD`   VARCHAR(20)  NULL     COMMENT '전표구분', -- ACC_CD
`IN_COST`  DECIMAL(10)  NULL     COMMENT '입고단가', -- IN_COST
`OUT_COST` DECIMAL(10)  NULL     COMMENT '출고단가', -- OUT_COST
`COMP_ID`  VARCHAR(20)  NULL     COMMENT '거래처ID', -- COMP_ID
`COMP_NM`  VARCHAR(100) NULL     COMMENT '거래처명', -- COMP_NM
`WH_CD`    VARCHAR(20)  NULL     COMMENT '창고코드', -- WH_CD
`WH_NM`    VARCHAR(100) NULL     COMMENT '창고명', -- WH_NM
`IN_WH_CD` VARCHAR(20)  NULL     COMMENT '받는창고', -- IN_WH_CD
`IN_WH_NM` VARCHAR(100) NULL     COMMENT '받는창고명', -- IN_WH_NM
`PROC_CD`  VARCHAR(20)  NULL     COMMENT '공정코드', -- PROC_CD
`PROC_NM`  VARCHAR(100) NULL     COMMENT '공정명', -- PROC_NM
`ITEM_DVN` VARCHAR(20)  NULL     COMMENT '품목구분', -- ITEM_DVN
`BARCODE`  VARCHAR(100) NULL     COMMENT '바콛', -- BARCODE
`WORK_ID`  VARCHAR(20)  NULL     COMMENT '담당자ID', -- WORK_ID
`WORK_NM`  VARCHAR(100) NULL     COMMENT '담당자명', -- WORK_NM
`REMARK`   VARCHAR(100) NULL     COMMENT '적요', -- REMARK
`SAFE_QTY` DECIMAL(10)  NULL     COMMENT '안전재고수량', -- SAFE_QTY
`ACC_NO`   VARCHAR(20)  NULL     COMMENT '전표번호', -- ACC_NO
`REG_ID`   VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID 
`REG_DTM`  VARCHAR(14)  NULL     COMMENT '등록일지', -- REG_DTM
PRIMARY KEY(DT_NO) 
)
COMMENT 'LOT Information';