CREATE TABLE `MYHH` (
	`MYHH_ID`     VARCHAR(15)  NOT NULL COMMENT 'MYHH ID', 
	`MYHH_NM`     VARCHAR(200) NULL     COMMENT 'MYHH 이름',  
	`USER_STS_YN` CHAR(1)      NULL     COMMENT '사용상태YN',
	`REG_DTM`     VARCHAR(14)  NULL     COMMENT '등록일시', 
	PRIMARY KEY(MYHH_ID)
)
COMMENT 'Myhh';
