CREATE TABLE `PROC_DTL_SUB` (
`ITEM_ID`  VARCHAR(20)  NOT NULL COMMENT '자재 ID', -- ITEM_ID
`SRC_CD`   VARCHAR(20)  NOT NULL COMMENT '재료코드', -- SRC_CD
`SEQ_NO`   DECIMAL(10)  NOT NULL COMMENT '작업순서', -- SEQ_NO
`SEQ_NM`   VARCHAR(20)  NULL     COMMENT '순서이름', -- SEQ_NM
`PROC_TIME` DECIMAL(5)  NULL     COMMENT '소요시간', -- PROC_TIME
`PROC_CD`  VARCHAR(20)  NULL     COMMENT '공정코드', -- PROC_CD
`PROC_NM`  VARCHAR(40)  NULL     COMMENT '공정이름', -- PROC_NM
`PROC_DTL` VARCHAR(500) NULL     COMMENT '설명', -- PROC_DTL
`CCP_YN`   CHAR(1)      NULL     COMMENT 'CCP구분', -- CCP_YN
`REG_ID`   VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID 
`REG_DTM`  VARCHAR(14)  NULL     COMMENT '등록일시', -- REG_DTM
PRIMARY KEY(ITEM_ID, SRC_CD, SEQ_NO)
)
COMMENT 'Process detail sub';