CREATE TABLE `PROD_INFO` (
	`ACC_NO`    VARCHAR(20)  NULL COMMENT '전표번호', -- ACC_NO
	`ITEM_ID`   VARCHAR(20)  NULL COMMENT '품목 ID', -- ITEM_ID
	`ITEM_NM`   VARCHAR(100) NULL COMMENT '품목이름', -- ITEM_NM
	`OUT_WH_NM` VARCHAR(100) NULL COMMENT '출고창고명', -- IN_WH_NM
	`IN_WH_NM`  VARCHAR(100) NULL COMMENT '입고창고명', -- IN_WH_NM2
	`SPEC`      VARCHAR(100) NULL COMMENT '규격', -- SPEC
	`QTY`       DECIMAL(10)  NULL COMMENT '수량', -- QTY
	`LOT_NO`    VARCHAR(300)  NULL COMMENT '로트 시리얼', -- LOT_NO
	`REMARK`    VARCHAR(100) NULL COMMENT '적요', -- REMARK
	`REG_ID`    VARCHAR(15)  NULL COMMENT '등록자ID', -- REG_ID 
	`REG_DTM`   VARCHAR(14)  NULL COMMENT '등록일자' -- REG_DTM 
)
COMMENT 'Production Information';