CREATE TABLE `SECU_DOC_MGMT` (
	`DOC_ID`  INT          NOT NULL AUTO_INCREMENT COMMENT '문서ID', -- DOC_ID
	`DOC_NM`  VARCHAR(100) NULL     COMMENT '문서이름', -- DOC_NM
	`DOC_DT`  VARCHAR(8)   NULL     COMMENT '등록일자', -- DOC_DT
	`ATT_DTM` VARCHAR(14)  NULL     COMMENT '첨부문서', -- ATT_DTM
	`FROM_DT` VARCHAR(8)   NULL     COMMENT '기간 From', -- FROM_DT
	`TO_DT`   VARCHAR(8)   NULL     COMMENT '기간 To', -- TO_DT
	`REG_ID`  VARCHAR(15)  NULL     COMMENT '등록자ID', -- REG_ID 
	`REG_DTM` VARCHAR(14)  NULL     COMMENT '등록일시', -- REG_DTM
	PRIMARY KEY(DOC_ID)
)
COMMENT 'Security Doc Management';