CREATE TABLE `WORKER_ATTN` (
`EMP_ID`  VARCHAR(15)  NOT NULL COMMENT '직원번호', -- EMP_ID
`ON_DTM`  VARCHAR(14)  NOT NULL COMMENT '출근일시', -- ON_DTM
`OFF_DTM` VARCHAR(14)  NULL     COMMENT '퇴근일시', -- OFF_DTM
`REMARK`  VARCHAR(200) NULL     COMMENT '비고', -- REMARK
PRIMARY KEY(EMP_ID , ON_DTM)
)
